version: "3"

services: 
  db:
    image: postgres:15-alpine
    container_name: cetepnews_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
